version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run:
          name: List bin dir
          command: |
            cd bin
            ls -al
            