version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install
          name: install npm packages
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install
          name: install npm packages
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test --runInBand || true
          name: Run tests
          no_output_timeout: 30m
      - store_test_results:
          path: tests/results

workflows:
  build_and_test:
    jobs:
      - build
      - test