version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run:
          name: Test env setup?
          command: |
            npm --version
            node --version
