version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          command: rm yarn.lock
          name: fix yarn?
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn install
          name: install node packages (node_modules)
      - run:
          command: yarn build
          build: build prettier into dist
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test --runInBand || true
          name: Run tests
          no_output_timeout: 30m

workflows:
  build_and_test:
    jobs:
      - build
      - test