version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node@5.0.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
