version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install
          name: install npm packages
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
  test: 
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install
          name: install npm packages
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test --runInBand || true
          name: Run tests
          no_output_timeout: 30m

wordkflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
 

