version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install
          name: install npm packages
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: |
            yarn test
          name: Run tests
          no_output_timeout: 30m
      - run:
          command: yarn build
          name: Build app
